name: CI - Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-api1:
    name: API1 - Testes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teste.pratico.api1   # ajuste para o nome real da pasta
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Rodar testes (API1)
        run: mvn -B -DskipTests=false test

  test-api2:
    name: API2 - Testes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teste.pratico.api2   # ajuste para o nome real da pasta
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Rodar testes (API2)
        run: mvn -B -DskipTests=false test
